name: libduo CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: libduo CI - test
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: sudo apt-get install -y gcc make libssl-dev cppcheck

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: ./configure && make

      - name: Static analysis
        run: cppcheck --quiet --force  --suppressions-list=.false_positive.txt --error-exitcode=1 .